ollama_host: "127.0.0.1"
ollama_port: 11434
ollama_model: "llama3.2"
ollama_style: "default"
ollama_pre_prompt: ""
database_url: "postgresql://postgres:postgres@db:5432/feverducation"
default_timezone: "UTC"
languages:
  - en
  - es
  - fr
jwt_secret_key: "supersecretkey"
jwt_algorithm: "HS256"
access_token_expires_minutes: 30
refresh_token_expires_minutes: 1440
