ollama_host: "127.0.0.1"
ollama_port: 11434
ollama_model: "llama3.2"
ollama_style: "default"
ollama_pre_prompt: ""
database_url: "postgresql://postgres:postgres@db:5432/feverducation"
default_timezone: "UTC"
languages:
  - en
  - es
  - fr
