version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: feverducation-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./config.yaml:/config.yaml:ro
    environment:
      - CONFIG_PATH=/config.yaml
      - PYTHONPATH=/app
    depends_on:
      - postgres
    networks:
      - feverducation-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: feverducation-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - feverducation-network

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: feverducation-postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=feverducation_password
      - POSTGRES_DB=feverducation
    networks:
      - feverducation-network

volumes:
  postgres-data:

networks:
  feverducation-network:
    driver: bridge