version: '3.8'

services:
  # Backend API Service
  backend:
    build: ./backend
    container_name: feverducation-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./config:/app/config
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - PYTHONPATH=/app
    command: bash -c "python backend/db/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
      - ollama
    networks:
      - feverducation-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: feverducation-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - feverducation-network

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: feverducation-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=feverducation_password
      - POSTGRES_DB=feverducation
    networks:
      - feverducation-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: feverducation-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - feverducation-network

  # PgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feverducation-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@feverducation.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    depends_on:
      - postgres
    networks:
      - feverducation-network

volumes:
  postgres-data:
  ollama-data:

networks:
  feverducation-network:
    driver: bridge