version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feverducation
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend API Service
  backend:
    build: ./backend
    container_name: feverducation-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./config.yaml:/config.yaml
    environment:
      - CONFIG_PATH=/config.yaml
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - feverducation-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: feverducation-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - feverducation-network

volumes:
  db-data:

networks:
  feverducation-network:
    driver: bridge