# CODEX: Development override for Docker Compose
# Enables hot-reload and bind mounts for faster iteration
services:
  backend:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
  frontend:
    command: sh -c "npm install && npm start"
    volumes:
      - ../frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
