version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feverducation
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
      - ../config.yaml:/config.yaml
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_ENABLE_REGISTER: "true"
    volumes:
      - ../frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  db-data:
