version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: feverducation-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: feverducation_password
      POSTGRES_DB: feverducation
    volumes:
      - ../backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - feverducation-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: feverducation-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ../config:/app/config
    environment:
      CONFIG_PATH: /app/config/config.yaml
      PYTHONPATH: /app
    command: bash -c "cp /app/config/config.yaml.example /app/config/config.yaml && python db/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
    networks:
      - feverducation-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: feverducation-frontend
    restart: always
    ports:
      - "5173:5173"
      - "1488:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - feverducation-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feverducation-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@feverducation.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    depends_on:
      - postgres
    networks:
      - feverducation-network

volumes:
  postgres-data:

networks:
  feverducation-network:
    driver: bridge
