# FeverDucation Platform Configuration

# Database Configuration
database:
  host: postgres
  port: 5432
  username: postgres
  password: feverducation_password
  database: feverducation

# Ollama Configuration
ollama:
  host: ollama
  port: 11434
  model: llama2
  context_window: 4096
  temperature: 0.7
  max_tokens: 2048

# Admin Configuration
admin:
  username: admin
  password: admin_password  # Will be hashed during initialization
  email: admin@feverducation.com

# Security Configuration
security:
  secret_key: "your_secret_key_here"  # Change in production
  algorithm: HS256
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7

# Server Configuration
server:
  host: 0.0.0.0
  port: 8000
  debug: true  # Set to false in production

# Frontend Configuration
frontend:
  url: http://localhost:3000
  api_url: http://localhost:8000/api

# Internationalization
i18n:
  default_language: en
  available_languages: [en, es]

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/feverducation.log

# Email Configuration (for notifications)
email:
  enabled: false
  smtp_server: smtp.example.com
  smtp_port: 587
  username: notifications@feverducation.com
  password: email_password
  from_email: notifications@feverducation.com